server:
    rundir: "/run/knot"
    user: knot:knot
    automatic-acl: on
    listen: 178.62.205.166@53
    listen: 2a03:b0c0:2:f0:0:1:e23:b001@53

log:
  - target: syslog
    any: info

database:
    storage: "/var/lib/knot"

mod-dnstap:
  - id: beacon_tap
    sink: unix:/run/knot-dnstap/dnstap.sock

template:
  - id: default
    storage: /var/lib/knot/zones
    # Ordered list of query modules applied to all queries
    global-module: mod-dnstap/beacon_tap
    file: "%s.zone"

remote:
#  - id: secondary
#    address: 192.168.1.1@53
#
#  - id: primary
#    address: 192.168.2.1@53


zone:
#    # Primary zone
  - domain: r.nossl.sh
    storage: /var/lib/knot/zones
    file: r.nossl.sh.zone

#    # Secondary zone
#  - domain: example.net
#    master: primary
